### PR TITLE
Zone.js in closure bundle (reduced bundle) & Bazel express server build

### PR DESCRIPTION
**Pull request by gregmagolan**
A way to bring zone.js into the bundle built by closure. This takes about 900 bytes off of the final compressed package size.

&

A Bazel built express server as a demonstration.

@alexeagle I had problems serving up the angular-bazel-example Angular app with the same express server as the app is built with "module":"commonjs" so the scripts are not easy to load in the browser. With this repo, the Angular app is nicely bundled into a single bundle.js that loads up easily.

### CODE REVIEW

**Review by alexeagle — COMMENTED** [review]
I think (?) this could be two separate PRs:
1. put zone.js inside the closure bundle (in this repo)
  we had it that way in the past, but Misko thinks it's better to treat zone.js as a "prollyfill" since he wants to get it on standards track. Also at some point, loading zone twice on the page didn't work, and it should be possible to closure-compile two different apps and bootstrap both on the same page

2. begin setup of server-side rendering, which could go in https://github.com/alexeagle/angular-bazel-example instead

**Comment by alexeagle** [comment]
oh, I understand now, you're using closure to convert commonjs to hoisted modules. that's an interesting workaround, but I don't think we want to have other people do that right now, it's pretty confusing, and closure is way too slow to be in the development round-trip.
@vsavkin does something similar but uses webpack to convert sources to browser-loadable instead of closure compiler.
I think the "right" way is https://github.com/bazelbuild/rules_typescript/issues/19

**Comment by gregmagolan** [comment]
Sure. I can separate the two and move the bazel express build to angular-bazel-example.

I'll check out bazelbuild/rules_typescript#19. If I can bundle/transform the Angular app there without closure so its not commonjs then it can be served up.

**Comment by gregmagolan** [comment]
"Also at some point, loading zone twice on the page didn't work, and it should be possible to closure-compile two different apps and bootstrap both on the same page"

That's interesting. I hadn't thought of that. Could bundle a polyfills.js in that case with closure and have zone in there as well as any other polyfills instead of loading zone.min.js directly.

**Comment by alexeagle** [comment]
In theory, zone.js should be stable and very CDN-cacheable (same with other
common polyfills) so you get less benefit bundling these together (if any
of them changes, the whole polyfill needs to be downloaded again).
But I'm not the expert on that :)
maybe we can just make zone.min.js smaller (optimize it with closure
compiler before publishing?)

Anyway I suspect this isn't the low-hanging-fruit of size reductions.

**Pull request closed without merging**
